### ISSUE TITLE
Split data (into train/test set) or not?

### ISSUE THREAD

**Issue by Tsinghua-gongjing** [yzhao062/pyod#103]
Hi,

I have a question about how to measure the model performance. Now I'm applying MCD method to my data (total sample number: 1580, features: 1000, outliner number: 40), the result is confusing.

As in the [benchmark.py](https://github.com/yzhao062/pyod/blob/master/notebooks/benchmark.py), the data is split and training and testing for 10 iterations. The code is as below:

![code](https://user-images.githubusercontent.com/12371558/58254762-05f8b180-7d9e-11e9-8ae9-071ab662ca1f.png)

The performance seems perfect (on testing set for 10 iterations):

![performance](https://user-images.githubusercontent.com/12371558/58254835-36405000-7d9e-11e9-94c1-8c2d12fdb45d.png)

However, while plotting the total reference data and predicted data, the performance looks bad (many of the common samples are predicted outliner).

![reference_vs_predict](https://user-images.githubusercontent.com/12371558/58255192-09406d00-7d9f-11e9-9f13-6af5a270ff38.png)

I can't understand the result well, why the AUC is so high but poor performance for total data. Is that caused by biased sampling in training process? If it is the case, does that mean splitting data (into train and test set) may be not a good idea for evaluating model performance (as the data set is so unbalanced)?

Best,
Jing

**Comment by yzhao062** [comment]
My best guess is the use of parameter `contaimination`. This parameter would control the number of outliers.

For instance, the raw score is [0.2, 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.3] and contamination==0.1, then the only the last item is going to be marked as 1, outlier. if contamination==0.2, then the first and the last will be marked as outliers.

I think you would want to make sure `contamination` is set to `the number outliers`/`the total numbers`.
If the data is public, feel free to share it and the code to reproduce.
