### ISSUE TITLE
Error during running of Autoencoder

### ISSUE THREAD

**Issue by lk1983823** [yzhao062/pyod#117]
I installed tensorflow 2.0 and keras 2.2.4 on my ubuntu 16.04.
However, when I run the toy code:
clf = AutoEncoder(epochs=30, contamination=contamination)
clf.fit(X_train)
Error shows:

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

This maybe due to the tensorflow and keras version.
After I change your code of Autoencoder imports to:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.losses import mean_squared_error It works.
So, I suggest there is a version specified requirements, of which the existed one is not clear enough.

**Comment by yzhao062** [comment]
Noted. Thanks for reporting this.

I read through some posts here: https://github.com/keras-team/keras/issues/12379 and guess it is a discrepancy between keras and tensorflow. 

Indeed, we forced the keras (and tensorflow) version before, but installing with pip may mess up users local installation. Some users reported and complained about this before... That is why we said users are responsible for keras and xgboost (similar reason) installation. 

For now, keras 2.2.4 and 1.14.0 should work. Hope this is helpful.
