### ISSUE TITLE
dropout_rate=0 fails on autoencoder

### ISSUE THREAD

**Issue by sbeaupre2** [yzhao062/pyod#118]
In auto_encoder.py there is this line which ensures the dropout parameter is valid. This fails when given 0 dropout due to the default behavior of not including the left bound. Also the param_name is set to alpha, leading to a misleading error message:

Error:
`ValueError: alpha is set to 0.0. Not in the range of (0, 1).`

Original code:
`check_parameter(dropout_rate, 0, 1, param_name='alpha')`

Fixed:
`check_parameter(dropout_rate, 0, 1, param_name='dropout_rate', include_left=True)`

**Comment by yzhao062** [comment]
Thanks for the note. PR is welcomed or I could fix it in the next version :)
