### ISSUE TITLE
Difference between training and testing phase for KNN

### ISSUE THREAD

**Issue by hajarhomayouni** [yzhao062/pyod#122]
What is the difference between the training phase and testing phase of KNN. I have split my dataset to training and testing sets and want to know how the invalidity scores are assigned to the testing samples after I fit the model on the training samples.

**Comment by yzhao062** [comment]
We know kNN is a lazy learner, so the training phase does not actually learn critical things--it is merely building a data structure to store the training points and calculate the outlier scores of the training samples, which are accessible once the model is fit. 

During the testing phase, the new sample will be measured by the training samples (identify the kth nearest neighbors of the test sample and report it as the outlier score of the sample)

**Comment by hajarhomayouni** [comment]
Based on what you say in the parenthesis, the outlier scores of testing samples are measured independent from the trained model?

**Comment by yzhao062** [comment]
yes or no. the outlier score of a new test sample x_t is the distance to its kth nearest neighbor among all training samples.

**Comment by hajarhomayouni** [comment]
Got it! thanks for the clarification!
