### ISSUE TITLE
Autoencoder prints summary every time

### ISSUE THREAD

**Issue by sbeaupre2** [yzhao062/pyod#123]
Not sure if this is an intended functionality, but every time an autoencoder is built, it prints the summary. It'd be nice if this was optional.

auto_encoder.py, line 183
`print(model.summary())`

**Comment by yzhao062** [comment]
I guess model summary is not a big issue. Printing details is mainly controlled by verbose parameter.

    verbose : int, optional (default=1)
        Verbosity mode.

        - 0 = silent
        - 1 = progress bar
        - 2 = one line per epoch.

        For verbosity >= 1, model summary may be printed.
