### ISSUE TITLE
Does autoencoder use values of target (y)

### ISSUE THREAD

**Issue by hajarhomayouni** [yzhao062/pyod#124]
I saw that y is optional in the fit(X, y=None) of autoencoder.
What if I give y as input? Does algorithm use the values of y?
Actually I have a dataset with labels for some but not all data points (labels include 0, 1, and None).
Does the algorithm perform a semi-supervised approach if I set y to the labels and give it as input to the fit function?

**Comment by yzhao062** [comment]
no...it is just a placeholder for consistency across unsupervised and supervised models, y will not be used in any form for autoencoder.
