### ISSUE TITLE
Question regarding the algorithms

### ISSUE THREAD

**Issue by quancore** [yzhao062/pyod#130]
I have 400K * 50 dataset, all numeric columns with a continuous numeric target variable. I have a supervised regression task. My aim to detect absolute outlier points that reduce the generalization power of regression models. Which outlier detection algorithms you suggest me? I thought to use an ensemble of several outlier detection algorithms but which ones are suitable for the dataset?

**Comment by yzhao062** [comment]
given your dataset, I will say try isolation forest first. It is much more scalable than most of the other algorithm. Be careful of setting "contaimination": the percent of the outliers you assume that hides in your data.
