### ISSUE TITLE
It is possible to perform fit and predict at the same time/dataset?

### ISSUE THREAD

**Issue by davidmguerra** [yzhao062/pyod#139]
I want to identify outliers in one dataset, but I don't want to split it into training and testing. How can I do this?

If I call both methods with the same data I think the result can be influenced (beyond unnecessary processing).

Thanks.

**Comment by yzhao062** [comment]
Indeed, you just need to fit the model with your entire training set.

clf.fit(X)

labels = clf.labels_
scores = clf.decision_scores_

The labels are simply converted from raw scores by marking top (% contamination) samples as outliers.
