### ISSUE TITLE
The questions about the implementation of the hbos

### ISSUE THREAD

**Issue by HiJuly** [yzhao062/Pyod#15]

**Comment by HiJuly** [comment]
from you implementation, for all feas including categorical and continuous, you do the same bins, is that propely？thanks

**Comment by HiJuly** [comment]
For each single feature (dimension), an univariate histogram is constructed
first. If the feature comprises of categorical data, simple counting of the values of
each category is performed and the relative frequency (height of the histogram)
is computed. For numerical features, two different methods can be used: (1)
Static bin-width histograms or (2) dynamic bin-width histograms.

**Comment by yzhao062** [comment]
@HiJuly thanks for reaching out. You are correct that the current HBOS is not handling any categorical features. All features/columns are treated equally by fitting histograms first. I am assuming this approach is valid given most categorical values may be unique. For instance, [a,b,v,c,s,d,s,d,s, e,n,c] has 8 unique values but 5 of them are unique with low frequency. **You are welcome to fork and implement the hbos which digest categorical as well, and we could merge that then**.

Another consideration is that data preprocessing is the responsibility of users, and we are not supposed to do the conversion for users, e.g. from categorical to numerical.

Feel free to share any thoughts:)
