### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [yzhao062/pyod#160]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./pyod/models/cblof.py:27: DeprecationWarning: invalid escape sequence \|
  """The CBLOF operator calculates the outlier score based on cluster-based
./pyod/models/xgbod.py:31: DeprecationWarning: invalid escape sequence \*
  """XGBOD class for outlier detection.
```

**Comment by yzhao062** [comment]
Hi. Thanks for noting me on this. I saw the PR and thanks for that. Just curious why only these two files throw the warning but not the rest as they use similar docstrings...

That will be nice if u could shed some light :)

**Comment by tirkarthi** [comment]
As per the error they have an invalid escape sequence while other docstrings don't. Upstream bug with more details https://bugs.python.org/issue32912

**Comment by yzhao062** [comment]
Thanks for the fix. Your PR #163 is now closed!
Thanks again :)
