### ISSUE TITLE
3D visualization for outlier detection(performance is ok.)

### ISSUE THREAD

**Issue by SungmanHong** [yzhao062/pyod#165]
Hello.
I coded the 3d outlier detection as below. (from pyod example)

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.font_manager

from pyod.models.abod import ABOD
from pyod.models.knn import KNN

from pyod.utils.data import generate_data, get_outliers_inliers

X_train, Y_train = generate_data(n_train=200,train_only=True, n_features=3)

outlier_fraction = 0.1

x_outliers, x_inliers = get_outliers_inliers(X_train,Y_train)

n_inliers = len(x_inliers)
n_outliers = len(x_outliers)

F1 = X_train[:,[0]].reshape(-1,1)
F2 = X_train[:,[1]].reshape(-1,1)
F3 = X_train[:,[2]].reshape(-1,1)

xx , yy, zz = np.meshgrid(np.linspace(-10, 10, 200), np.linspace(-10, 10, 200), np.linspace(-10, 10, 200))
xxx , yyy = np.meshgrid(np.linspace(-10, 10, 200), np.linspace(-10, 10, 200))

from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(F1, F2, F3)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

classifiers = {
     'K Nearest Neighbors (KNN)' :  KNN(contamination=outlier_fraction),
     'Angle-based Outlier Detector (ABOD)'   : ABOD(contamination=outlier_fraction)
}

plt.figure(figsize=(10, 10))

for i, (clf_name,clf) in enumerate(classifiers.items()) :
    # fit the dataset to the model
    clf.fit(X_train)
    scores_pred = clf.decision_function(X_train)*-1
    y_pred = clf.predict(X_train)
    n_errors = (y_pred != Y_train).sum()
    print('No of Errors : ',clf_name, n_errors)
    threshold = stats.scoreatpercentile(scores_pred,100 *outlier_fraction)

it's works.
but when i commit the next line below

    Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel(), zz.ravel()]) * -1

it stops....
Can i get the visualization part for getting the decision reigion?

**Comment by SungmanHong** [comment]
from the 

Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel(), zz.ravel()]) * -1

line, when i want to the decision_function of 3D input data,
how to code it?? am I right? the decision function of 3D input data is 2D output?
I'm afraid that np.c_ returns 1D output and am i wrong.

**Comment by yzhao062** [comment]
np.c_[xx.ravel(), yy.ravel(), zz.ravel() results in a [200*200*200, 3] matrix, which is not desired. 
That is why it never converges
