### ISSUE TITLE
myBinder not initializing

### ISSUE THREAD

**Issue by raybellwaves** [yzhao062/pyod#199]
https://mybinder.org/v2/gh/yzhao062/pyod/master

![image](https://user-images.githubusercontent.com/17162724/83920439-36fa1900-a74a-11ea-906e-7b7779eeb8a6.png)

**Comment by yzhao062** [comment]
Thanks! This is indeed a bug. Will fix

**Comment by yzhao062** [comment]
It should be fixed now. compare_all_models.py has an bug tho.
