### ISSUE TITLE
cannot import name 'get_color_codes' from 'pyod.utils.data'

### ISSUE THREAD

**Issue by nuomizai** [yzhao062/pyod#204]
When I tried to use the visualization example in doc [pyod](https://pyod.readthedocs.io/en/stable/_modules/examples/knn_example.html#visualize), the error occurred as:

`cannot import name 'get_color_codes' from 'pyod.utils.data'`

But I haved installed pyod correctly.

**Comment by nuomizai** [comment]
I solved this by importing the visualize funciton in pyod as

`from pyod.utils.example import visualize`

It seemed that the doc [pyod](https://pyod.readthedocs.io/en/stable/_modules/examples/knn_example.html#visualize) need some improvement.

**Comment by yzhao062** [comment]
yeah. that is because you are viewing an old version doc "stable". Has disabled it

See the latest here: https://pyod.readthedocs.io/en/latest/

thanks for the note.
