### ISSUE TITLE
Which PYOD models are good with univariate data?

### ISSUE THREAD

**Issue by gireeshkbogu** [yzhao062/pyod#205]
Hi, is PYOD only for multivariate data or any of the models can be applied to univariate data?

**Comment by yzhao062** [comment]
for univariate data, I guess classical 2 sigma or 3 sigma method should be sufficient? something like this: https://machinelearningmastery.com/how-to-use-statistics-to-identify-outliers-in-data/

**Comment by davidusb-geek** [comment]
A solution could be to create a new "lag" column using something like `df['lag']=df['data'].shift()` and then can use whatever method you want from Pyod.

**Comment by John-Almardeny** [comment]
From PyOD, you can use [LMDD](https://github.com/yzhao062/pyod/blob/master/pyod/models/lmdd.py) algorithm for unvariate data.
Outside PyOD, the MAD algorithm has proved being a robust detector for univariate data, since it still works when data distribution is not Gaussian-like.
