### ISSUE TITLE
Distribute on Apache Spark cluster

### ISSUE THREAD

**Issue by ottok92** [yzhao062/pyod#215]
Hello there.

In your documentation you assert that:
"Optimized performance with JIT and parallelization when possible, using numba and joblib."

However, there is no documentation regarding how to actually make use of parallel processing with PyOD. I am curerntly working with a Spark cluster and would be much obliged if I could distribute the fit process of KNN onto my workers.

I have tried registering spark as the backend for joblib with [joblib-spark](https://github.com/joblib/joblib-spark). It has worked with Scikit-Learn but I have had no success with PyOD so far.

**Comment by ottok92** [comment]
I found out what the problem was. Registering a spark backend is not enough.
The KNN object should be initialized with the @param "n_jobs" set to the
number of CPUs (`-1` for all cores).
Furthermore, the `fit` method must be called within the block `with
parallel_backend('spark', n_jobs=-1)`.
An example follows:

``` python
from pyod.models.knn import KNN
from joblibspark import register_spark
from sklearn.utils import parallel_backend

register_spark()

knn = KNN(n_jobs=-1)

with parallel_backend('spark', n_jobs=-1):
    knn_model = knn.fit(X_train)
```

I hope it serves as help to others in the future.

**Comment by SaqlainHussainShah** [comment]
@ottok92 Can you please share reference/link for "Optimized performance with JIT and parallelization when possible, using numba and joblib". Also how can I register spark as the backend for joblib with joblib-spark.

**Comment by rupesh15203** [comment]
@ottok92 I am using same logic for finding outlier in car pricing:
```
knn = KNN(n_jobs=-1)
with parallel_backend('spark', n_jobs=-1):
    knn_model = knn.fit(df.select(df.columns))
```
Here df is spark dataframe. But when I ran this code somehow model is only loading df schema as follows:
```
ValueError: Expected 2D array, got scalar array instead:
array=DataFrame[length: double, width: double, height: double, engine-size: int, price: int].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
What I am missing here. Thanks in advance.

**Comment by molgun** [comment]
@rupesh15203 I think it's about your dataframe broh. Sorry for the late reply.

**Comment by SaqlainHussainShah** [comment]
Thanks molgun
