### ISSUE TITLE
Mistake in ReadTheDocs generate_data function

### ISSUE THREAD

**Issue by Nexxel** [yzhao062/pyod#223]
pyod.utils.data.generate_data, it is said the next one about the 'behaviour' parameter: 'Behaviour of the returned datasets which can be either ‘old’ or ‘new’. Passing behaviour='new' returns “X_train, y_train, X_test, y_test”, while passing behaviour='old' returns “X_train, X_test, y_train, y_test”.'

I've check that it is in the wrong way and it should be 'Behaviour of the returned datasets which can be either ‘old’ or ‘new’. Passing behaviour='new' returns “X_train, X_test, y_train, y_test”, while passing behaviour='old' returns “X_train, y_train, X_test, y_test”.' as the returns are of the other behaviour.

**Comment by mstapfner** [comment]
+1 i also ran into this issue.

**Comment by yzhao062** [comment]
Thanks for notifying us! We just fixed the documentation :)
