### ISSUE TITLE
Wrong Label  on method SOGAAL and MOGAAL

### ISSUE THREAD

**Issue by luisfelipe18** [yzhao062/pyod#237]
On the original paper from Xiangnan He, the inliers are marked as 1 and outliers marked as 0. I checked their original code and the code of pyod line by line and are almost the same.
On the line [https://github.com/yzhao062/pyod/blob/94c27ef3841de4b0e5a732f9c720092a24397633/pyod/models/mo_gaal.py#L79](url) you state 0 for inliers and 1 for outliers , but in the original paper at page 3, section 3.1, third and fourth line says 0 outlier, 1 inlier. [https://arxiv.org/pdf/1809.10816.pdf](url)

**Comment by yzhao062** [comment]
This is a good point and potentially a bug. I did not implement this algorithm by myself and need some probing. In the worst case, it is incorrect and we need to flip the score and also the score.

**Comment by luisfelipe18** [comment]
![image](https://user-images.githubusercontent.com/25039923/94628013-3565db00-027c-11eb-951f-969dfa011125.png)

in the line 11, from `principalDf["resultado"] = principalDf["resultado"].map({0:"b",1:"r"})`, I am mapping 0 to "b" and 1 to "r".

As you can see, the lower proportion is "b" which are equivalents to `0`. (This `0` and `1` comes from `model.predict` . Since docs says `0` must be a inlier and it appears in lower proportion I started to think that something is wrong.

**Comment by anranhui** [comment]
I also encountered this error, sogaal original 1 is normal data, but in pyod, 0 is normal data

**Comment by zhaoxing-zstar** [comment]
I compare the results between SO_GAAL and other algorithms, and I think the score for SO_GAAL should be flipped (0 for outlier, 1 for normal). Maybe overriding the `_process_decision_score` method would work.

**Comment by yzhao062** [comment]
I suspect that guys...
This is the sogaal example with a simple synthetic data.

![image](https://user-images.githubusercontent.com/15079146/164134984-434f9a1f-ee09-4fae-80e2-8590b91607b2.png)

if I flip the score by -1, the performance looks incorrect.
![image](https://user-images.githubusercontent.com/15079146/164135247-d5f34b46-13ab-42ea-aba7-0a100c07fbba.png)

Maybe I miss some points?

**Comment by zhaoxing-zstar** [comment]
Very simple example here

```python
from pyod.models.so_gaal import SO_GAAL
from pyod.utils.data import generate_data
from pyod.utils.data import evaluate_print

X_train, y_train, X_test, y_test = generate_data(
            n_train=1000, n_test=100,
            n_features=100, contamination=0.1,
            random_state=42)

clf_name = "SO_GAAL"
clf = SO_GAAL(contamination=0.1, stop_epochs = 10)
clf.fit(X_train)

y_train_pred = clf.labels_  # binary labels (0: inliers, 1: outliers)
y_train_scores = clf.decision_scores_  # raw outlier scores

y_test_pred = clf.predict(X_test)
y_test_scores = clf.decision_function(X_test)

print(f"Train {evaluate_print(clf_name, y_train, y_train_scores)}")
print(f"Train {evaluate_print(clf_name, y_test, y_test_scores)}")
```
The result:
![output](https://user-images.githubusercontent.com/60384317/164140890-4b365165-b8b0-484f-9b99-6f98abb67890.png)
If we flip the score, the result would be correct. So, I guess the difference comes from the different labeling methods of the original data set, whether 0/1 is the outlier.

**Comment by zhaoxing-zstar** [comment]
> I suspect that guys... This is the sogaal example with a simple synthetic data.
> 
> ![image](https://user-images.githubusercontent.com/15079146/164134984-434f9a1f-ee09-4fae-80e2-8590b91607b2.png)
> 
> if I flip the score by -1, the performance looks incorrect. ![image](https://user-images.githubusercontent.com/15079146/164135247-d5f34b46-13ab-42ea-aba7-0a100c07fbba.png)
> 
> Maybe I miss some points?

My fault, you're right.

**Comment by anranhui** [comment]
In principle, so Gaal should be such a process

The outliers are separated by positive and negative samples. However, too many training rounds of the generator may cause the negative samples to be too close to the positive samples, so the performance will be reduced.
To solve this problem, I have further studied and found another way to better isolate outliers. At present, I am writing a paper






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzhao062/pyod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzhao062/pyod] Wrong Label  on method SOGAAL and MOGAAL (#237)





 
I suspect that guys...
 This is the sogaal example with a simple synthetic data.
 

 
if I flip the score by -1, the performance looks incorrect.
 
 
Maybe I miss some points?

**Comment by anranhui** [comment]
In principle, so Gaal should be such a process，The outlier is actually x, and there is a problem with the legend

The outliers are separated by positive and negative samples. However, too many training rounds of the generator may cause the negative samples to be too close to the positive samples, so the performance will be reduced.
To solve this problem, I have further studied and found another way to better isolate outliers. At present, I am writing a paper






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yzhao062/pyod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzhao062/pyod] Wrong Label  on method SOGAAL and MOGAAL (#237)





 
I suspect that guys...
 This is the sogaal example with a simple synthetic data.
 

 
if I flip the score by -1, the performance looks incorrect.
 
 
Maybe I miss some points?

**Comment by yzhao062** [comment]
looking forward to knowing more about the progress. good luck with the paper.
