### ISSUE TITLE
Implement Rapid Distance-Based Outlier Detection via Sampling (Sp)

### ISSUE THREAD

**Issue by durgeshsamariya** [yzhao062/pyod#251]
See https://papers.nips.cc/paper/2013/file/d296c101daa88a51f6ca8cfc1ac79b50-Paper.pdf for more information.

**Comment by tam17aki** [comment]
Hi,

I have recenlty implemented the method in PyOD format.

Python code
https://gist.github.com/tam17aki/b918a0e7c41d569515e0ae77875983fc

example notebook
https://gist.github.com/tam17aki/283fdacbc1ceb345768989d2ef266a69

benchmark notebook
https://gist.github.com/tam17aki/cea0c260b6c2fedcb919296a74f71b72

Best regards,
Akira

**Comment by yzhao062** [comment]
if you consider adding it to the pyod, feel free to submit a PR. it will look like https://github.com/yzhao062/pyod/pull/377

one main file, one example file, and one test file.

thanks!

**Comment by durgeshsamariya** [comment]
I also implemented that in PyOD format.

Anyways, thanks for submitting that in PyOD. 

> Hi,
> 
> I have recenlty implemented the method in PyOD format.
> 
> Python code https://gist.github.com/tam17aki/b918a0e7c41d569515e0ae77875983fc
> 
> example notebook https://gist.github.com/tam17aki/283fdacbc1ceb345768989d2ef266a69
> 
> benchmark notebook https://gist.github.com/tam17aki/cea0c260b6c2fedcb919296a74f71b72
> 
> Best regards, Akira
