### ISSUE TITLE
COPOD docs incorrect

### ISSUE THREAD

**Issue by julienschuermans** [yzhao062/pyod#258]
The COPOD docs report that `explain_outlier` returns a matplotlib plot,
but it returns a tuple of pandas Series with the plot data.

**Comment by nbijlani** [comment]
COPOD explain_outlier method fails when used as described. The error is 'numpy.ndarray' object has no attribute 'columns' when the columns argument is not supplied. And 'numpy.ndarray' object has no attribute 'loc' when the columns argument is supplied.

**Comment by yzhao062** [comment]
This is a bug. We originally use pandas for COPOD and then replace it with numpy, where col and loc are no longer working. Will have a fix. Thanks for reporting.

**Comment by nbijlani** [comment]
Thank you! It would be great to have this fixed. The outlier visualization would be a key feature for our healthcare application. Thanks.

**Comment by yzhao062** [comment]
As a temporary solution (until we have a fix), you could use PyOD V0.9.0 or earlier.

pip install pyod==0.9.0

I will report back in #337 for the latest fix.
