### ISSUE TITLE
ABOD decision score

### ISSUE THREAD

**Issue by celineinc** [yzhao062/pyod#262]
Hi, 
Thank you for making this library, I'm currently using it for my Data Mining course assignments. I have a question.

Why did you flip the decision score value? [ABOD code line 177](https://github.com/yzhao062/pyod/blob/master/pyod/models/abod.py)
```
# flip the scores
        self.decision_scores_ = self.decision_scores_.ravel() * -1
        self._process_decision_scores()
        return self
```
Isn't the definition of outliers in ABOD "a point whose wocs variance is small" (Kriegel, Schubert, & Zimek, 2008; Pham & Pagh, 2012)? So I think the decision score for outliers should be lower, not higher as written in [the documentation](https://pyod.readthedocs.io/en/latest/pyod.models.html#pyod.models.abod.ABOD.decision_scores_). You shouldn't flip it by multiplying with -1.

References:
- [Kriegel, H. P., Schubert, M., & Zimek, A. (2008, August). Angle-based outlier detection in high-dimensional data. In _Proceedings of the 14th ACM SIGKDD international conference on Knowledge discovery and data mining_ (pp. 444-452).](https://dl.acm.org/doi/pdf/10.1145/1401890.1401946)
- [Pham, N., & Pagh, R. (2012, August). A near-linear time approximation algorithm for angle-based outlier detection in high-dimensional data. In _Proceedings of the 18th ACM SIGKDD international conference on Knowledge discovery and data mining_ (pp. 877-885)](https://dl.acm.org/doi/pdf/10.1145/2339530.2339669)

**Comment by yzhao062** [comment]
Exactly. Smaller means more outlyingness. So wcos is multiplied with -1 to flip the direction.
To have all models consistent, we define the larger the output scores (-wcos), the more outlying the sample is.
![image](https://user-images.githubusercontent.com/15079146/102228382-a2226600-3eb8-11eb-894d-4c483c6e0954.png)

If I remove the -1, abod_example will result in wrong result. Hope this helps.

**Comment by celineinc** [comment]
Thank you so much for the response 👍😃. But I still don't really understand why. By having all models consistent, do you mean with other models non-ABOD? If you don't mind, can you please explain why it will go wrong if you remove -1? 

Thank you in advance.

**Comment by yzhao062** [comment]
I think the confusion is about wcos...indeed, it is the variance of all wcos. So smaller variance means the anomaly is on the same side of all normal points, somehow like that. So anomalies have smaller variance of wcos.
