### ISSUE TITLE
"Sklearn version error" with scikit-learn>=0.24.0

### ISSUE THREAD

**Issue by Yard1** [yzhao062/pyod#265]
With the newly released scikit-learn 0.24.0, pyod is unusable due to the `"Sklearn version error"` exception. From reading the release notes, it does not look like there are any changes that would break pyod, therefore it should be just a matter of changing the version check to allow for 0.24.0 as well.

**Comment by KirilIakovliev** [comment]
same problem

**Comment by yzhao062** [comment]
thanks for the note. the first thing to investigate today.

Just wonder if u could share the exact error message? 

I could see some import error on the test suite sides, but not sure why that will prevent installation.
https://travis-ci.org/github/yzhao062/pyod/jobs/751038877

thanks again

**Comment by yzhao062** [comment]
checked the sklearn update log: https://scikit-learn.org/stable/whats_new/v0.24.html

looks like nothing should be broken...will investigate. 

Just to confirm the error happens when you try to pip install pyod right?

**Comment by Yard1** [comment]
```
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pyod/models/knn.py:17: in <module>
    from .base import BaseDetector
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pyod/models/base.py:15: in <module>
    if _get_sklearn_version() > 20:
/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pyod/utils/utility.py:446: in _get_sklearn_version
    raise ValueError("Sklearn version error")
E   ValueError: Sklearn version error
```
This exception seems to appear when `pyod` is imported. Using the latest pip release.

**Comment by yzhao062** [comment]
This helps. Will have a fix today :)

Thanks again!

**Comment by yzhao062** [comment]
It is fixed and tested on a new env. use 0.8.5 :)

![image](https://user-images.githubusercontent.com/15079146/102953280-ee643c00-449e-11eb-9f09-acd000744c83.png)
