### ISSUE TITLE
ERROR: from pyod.models.combination      import average → No module named 'sklearn.utils.testing'

### ISSUE THREAD

**Issue by MichalRIcar** [yzhao062/pyod#276]
Hello,

with the recent release of sklearn I am facing error of pyod just at the very beginning - import the package :

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-06b92f414d46> in <module>
     25 from pyod.models.iforest          import IForest
     26 from pyod.models.knn              import KNN
---> 27 **from pyod.models.combination      import average**
     28 

~\anaconda3\lib\site-packages\pyod\models\combination.py in <module>
      8 from __future__ import print_function
      9 
---> 10 from combo.models.score_comb import aom as combo_aom
     11 from combo.models.score_comb import moa as combo_moa
     12 from combo.models.score_comb import average as combo_average

~\anaconda3\lib\site-packages\combo\models\score_comb.py in <module>
     14 from sklearn.utils.extmath import weighted_mode
     15 from sklearn.utils.random import sample_without_replacement
---> 16 **from sklearn.utils.testing import assert_equal**
     17 from sklearn.utils.multiclass import check_classification_targets
     18 

**ModuleNotFoundError: No module named 'sklearn.utils.testing'**

**Comment by yzhao062** [comment]
please update combo library to 0.1.2

pip install combo --upgrade

**Comment by MichalRIcar** [comment]
solved, thank you!
