### ISSUE TITLE
What kind of model is adapted for kind of features? 

### ISSUE THREAD

**Issue by cfrancois7** [yzhao062/pyod#277]
I explored many of outlier detector from PyOD packages.
But some of them are adapted for specific kind of features, i.e. gaussian ones, or monotonic ones.

It should be great to have this kind of information, briefly in the document. Kind of recommandation: "this model are effecient for gaussian features; for small quantity of features (< 50 features), or huge quantity of sample (> 1000 samples), etc...".

I'm still exploring the results and reaction of many PyOD model and oftentimes I've poor results. Even in the papers/references it not always clear enough what kind of features is expected for the models.

Maybe you master the models because you build the PyOD package, so you know what kind of model match well these or these kind of features.

**Comment by yzhao062** [comment]
this is a good point. The difficulty is exactly as you mentioned...unsupervised outlier detection is challenging and we do not know when and whether a certain algorithm could work for a specific dataset. For now, it is still trials and errors.

We have some knowledge about the running time but not exactly about the model performance...
