### ISSUE TITLE
Installing pyod inside a docker container.

### ISSUE THREAD

**Issue by tristantoupin** [yzhao062/pyod#280]
I'm having difficulties installing pyod with pip inside a docker container. I understand it has to do with numba when installing llvmlite. I tried installing it manually but no luck.. I am running Docker version 20.10.1, build 831ebeae96, on a MacBook Pro M1 2020.

Here's the stack trace from the command 
`
docker build .
`

<pre><code>[+] Building 493.8s (7/7) FINISHED                                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                                       0.5s
 => => transferring dockerfile: 135B                                                                                                                                                       0.1s
 => [internal] load .dockerignore                                                                                                                                                          0.3s
 => => transferring context: 2B                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.8                                                                                                                              1.1s
 => [internal] load build context                                                                                                                                                          0.4s
 => => transferring context: 47B                                                                                                                                                           0.1s
 => CACHED [1/3] FROM docker.io/library/python:3.8@sha256:333e793b39e6a2d349c2ec91780df36750cc0760a05f3b22a4dced5fc6d74b4f                                                                 0.0s
 => [2/3] COPY requirements.txt requirements.txt                                                                                                                                           0.6s
 => ERROR [3/3] RUN pip install -r requirements.txt                                                                                                                                      490.9s
------                                                                                                                                                                                          
 > [3/3] RUN pip install -r requirements.txt:                                                                                                                                                   
#7 2.321 Collecting pyod                                                                                                                                                                        
#7 2.461   Downloading pyod-0.8.6.tar.gz (98 kB)                                                                                                                                                
#7 2.920 Collecting combo                                                                                                                                                                       
#7 2.944   Downloading combo-0.1.2.tar.gz (37 kB)                                                                                                                                               
#7 3.228 Collecting joblib
#7 3.257   Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
#7 3.577 Collecting matplotlib
#7 3.598   Downloading matplotlib-3.3.4.tar.gz (37.9 MB)
#7 14.00 Collecting numpy>=1.13
#7 14.09   Using cached numpy-1.20.1-cp38-cp38-manylinux2014_aarch64.whl (12.7 MB)
#7 14.28 Collecting numba>=0.35
#7 14.31   Downloading numba-0.52.0.tar.gz (2.1 MB)
#7 16.38 Collecting pandas>=0.25
#7 16.41   Downloading pandas-1.2.2-cp38-cp38-manylinux2014_aarch64.whl (10.0 MB)
#7 18.12 Collecting scipy>=0.19.1
#7 18.15   Downloading scipy-1.6.0-cp38-cp38-manylinux2014_aarch64.whl (26.1 MB)
#7 22.08 Collecting scikit_learn>=0.19.1
#7 22.11   Downloading scikit-learn-0.24.1.tar.gz (7.4 MB)
#7 23.51   Installing build dependencies: started
#7 31.35   Installing build dependencies: finished with status 'done'
#7 31.36   Getting requirements to build wheel: started
#7 31.61   Getting requirements to build wheel: finished with status 'done'
#7 31.61     Preparing wheel metadata: started
#7 31.81     Preparing wheel metadata: finished with status 'done'
#7 31.91 Collecting six
#7 31.95   Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
#7 32.12 Collecting statsmodels
#7 32.15   Downloading statsmodels-0.12.2.tar.gz (17.5 MB)
#7 35.59   Installing build dependencies: started
#7 103.9   Installing build dependencies: still running...
#7 108.9   Installing build dependencies: finished with status 'done'
#7 108.9   Getting requirements to build wheel: started
#7 158.3   Getting requirements to build wheel: finished with status 'done'
#7 158.3     Preparing wheel metadata: started
#7 158.7     Preparing wheel metadata: finished with status 'done'
#7 158.8 Collecting suod
#7 158.8   Downloading suod-0.0.6.tar.gz (2.1 MB)
#7 159.5 Collecting llvmlite<0.36,>=0.35.0
#7 159.5   Downloading llvmlite-0.35.0.tar.gz (121 kB)
#7 159.7 Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from numba>=0.35->pyod->-r requirements.txt (line 1)) (53.0.0)
#7 159.8 Collecting pytz>=2017.3
#7 159.8   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
#7 160.1 Collecting python-dateutil>=2.7.3
#7 160.1   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
#7 160.3 Collecting threadpoolctl>=2.0.0
#7 160.3   Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
#7 160.5 Collecting cycler>=0.10
#7 160.5   Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
#7 160.6 Collecting kiwisolver>=1.0.1
#7 160.7   Downloading kiwisolver-1.3.1-cp38-cp38-manylinux2014_aarch64.whl (78 kB)
#7 161.1 Collecting pillow>=6.2.0
#7 161.2   Downloading Pillow-8.1.0-cp38-cp38-manylinux2014_aarch64.whl (2.2 MB)
#7 161.7 Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
#7 161.7   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
#7 161.9 Collecting patsy>=0.5
#7 161.9   Downloading patsy-0.5.1-py2.py3-none-any.whl (231 kB)
#7 162.2 Collecting psutil
#7 162.2   Downloading psutil-5.8.0.tar.gz (470 kB)
#7 162.5 Building wheels for collected packages: pyod, numba, llvmlite, scikit-learn, combo, matplotlib, statsmodels, suod, psutil
#7 162.5   Building wheel for pyod (setup.py): started
#7 162.6   Building wheel for pyod (setup.py): finished with status 'done'
#7 162.6   Created wheel for pyod: filename=pyod-0.8.6-py3-none-any.whl size=112145 sha256=eb8f7e583c4105e7378f532d164c860c97b7ea7842f5a20adbc77de1f43fa24d
#7 162.6   Stored in directory: /root/.cache/pip/wheels/94/9b/33/a245c7f9156010196e279d3bac735a47e65f1effb4157df186
#7 162.6   Building wheel for numba (setup.py): started
#7 162.7   Building wheel for numba (setup.py): finished with status 'error'
#7 162.7   ERROR: Command errored out with exit status 1:
#7 162.7    command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hxu1ee9y
#7 162.7        cwd: /tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/
#7 162.7   Complete output (7 lines):
#7 162.7   Traceback (most recent call last):
#7 162.7     File "<string>", line 1, in <module>
#7 162.7     File "/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py", line 413, in <module>
#7 162.7       metadata['ext_modules'] = get_ext_modules()
#7 162.7     File "/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py", line 148, in get_ext_modules
#7 162.7       import numpy.distutils.misc_util as np_misc
#7 162.7   ModuleNotFoundError: No module named 'numpy'
#7 162.7   ----------------------------------------
#7 162.7   ERROR: Failed building wheel for numba
#7 162.7   Running setup.py clean for numba
#7 162.8   ERROR: Command errored out with exit status 1:
#7 162.8    command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
#7 162.8        cwd: /tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057
#7 162.8   Complete output (7 lines):
#7 162.8   Traceback (most recent call last):
#7 162.8     File "<string>", line 1, in <module>
#7 162.8     File "/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py", line 413, in <module>
#7 162.8       metadata['ext_modules'] = get_ext_modules()
#7 162.8     File "/tmp/pip-install-64twn51n/numba_d4ff7c97b2304f8cb55048d241635057/setup.py", line 148, in get_ext_modules
#7 162.8       import numpy.distutils.misc_util as np_misc
#7 162.8   ModuleNotFoundError: No module named 'numpy'
#7 162.8   ----------------------------------------
#7 162.8   ERROR: Failed cleaning build dir for numba
#7 162.8   Building wheel for llvmlite (setup.py): started
#7 162.9   Building wheel for llvmlite (setup.py): finished with status 'error'
#7 162.9   ERROR: Command errored out with exit status 1:
#7 162.9    command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sxwrx19h
#7 162.9        cwd: /tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/
#7 162.9   Complete output (26 lines):
#7 162.9   running bdist_wheel
#7 162.9   /usr/local/bin/python /tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py
#7 162.9   LLVM version... Traceback (most recent call last):
#7 162.9     File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 105, in main_posix
#7 162.9       out = subprocess.check_output([llvm_config, '--version'])
#7 162.9     File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
#7 162.9       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#7 162.9     File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
#7 162.9       with Popen(*popenargs, **kwargs) as process:
#7 162.9     File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
#7 162.9       self._execute_child(args, executable, preexec_fn, close_fds,
#7 162.9     File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
#7 162.9       raise child_exception_type(errno_num, err_msg, err_filename)
#7 162.9   FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
#7 162.9   
#7 162.9   During handling of the above exception, another exception occurred:
#7 162.9   
#7 162.9   Traceback (most recent call last):
#7 162.9     File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 191, in <module>
#7 162.9       main()
#7 162.9     File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 181, in main
#7 162.9       main_posix('linux', '.so')
#7 162.9     File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 107, in main_posix
#7 162.9       raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
#7 162.9   RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
#7 162.9   error: command '/usr/local/bin/python' failed with exit status 1
#7 162.9   ----------------------------------------
#7 162.9   ERROR: Failed building wheel for llvmlite
#7 162.9   Running setup.py clean for llvmlite
#7 162.9   Building wheel for scikit-learn (PEP 517): started
#7 225.7   Building wheel for scikit-learn (PEP 517): still running...
#7 287.2   Building wheel for scikit-learn (PEP 517): still running...
#7 342.7   Building wheel for scikit-learn (PEP 517): finished with status 'done'
#7 342.8   Created wheel for scikit-learn: filename=scikit_learn-0.24.1-cp38-cp38-linux_aarch64.whl size=24226574 sha256=fe2fbe0995a38049f2d533435619e60532fb672a20a2656cc0c3741bb8c51131
#7 342.8   Stored in directory: /root/.cache/pip/wheels/b4/de/0e/b6566d7ce80b8689ba6044ba324fe3acf149a784626c7be120
#7 342.8   Building wheel for combo (setup.py): started
#7 343.0   Building wheel for combo (setup.py): finished with status 'done'
#7 343.0   Created wheel for combo: filename=combo-0.1.2-py3-none-any.whl size=42026 sha256=3a0dbd1b93742a66f4e2ebdf0f356fb79ccc4e4ccb1f62597c0f8fdc5c10b2ca
#7 343.0   Stored in directory: /root/.cache/pip/wheels/40/d4/93/ea2224f96bd2868538da3b8231211c42632221600b080ddf16
#7 343.0   Building wheel for matplotlib (setup.py): started
#7 379.9   Building wheel for matplotlib (setup.py): finished with status 'done'
#7 379.9   Created wheel for matplotlib: filename=matplotlib-3.3.4-cp38-cp38-linux_aarch64.whl size=9889551 sha256=fc3bec328bddcf1c4ea20443024b31b733ca32bdc2cd9f7515fad64a6e4c22c5
#7 379.9   Stored in directory: /root/.cache/pip/wheels/10/b2/01/f5924439214e73e2c6dc1072b8f87b55ae3017968574ed77bc
#7 379.9   Building wheel for statsmodels (PEP 517): started
#7 442.8   Building wheel for statsmodels (PEP 517): still running...
#7 485.1   Building wheel for statsmodels (PEP 517): finished with status 'done'
#7 485.1   Created wheel for statsmodels: filename=statsmodels-0.12.2-cp38-cp38-linux_aarch64.whl size=22004953 sha256=58a80bf3401933df921ef2048a1253fb6029bf3ce9be8cd471297a2608929010
#7 485.1   Stored in directory: /root/.cache/pip/wheels/7b/bf/91/ed8052c0ed1bce63ab3cfc9ad51218518f41ab34d61f398140
#7 485.1   Building wheel for suod (setup.py): started
#7 485.4   Building wheel for suod (setup.py): finished with status 'done'
#7 485.4   Created wheel for suod: filename=suod-0.0.6-py3-none-any.whl size=2154760 sha256=82c9b4a8052a2df96c867fd88ebcacd245ae5305e688b861236b0e058fc981eb
#7 485.4   Stored in directory: /root/.cache/pip/wheels/70/9e/be/b319e3ee58403b9e71ecb496109ae5bdc4da57aeb472ebe114
#7 485.4   Building wheel for psutil (setup.py): started
#7 486.0   Building wheel for psutil (setup.py): finished with status 'done'
#7 486.0   Created wheel for psutil: filename=psutil-5.8.0-cp38-cp38-linux_aarch64.whl size=298628 sha256=daee182a9c938224fa6ad36dceb7ec98249cb05f3fee869252595af58f58e5c2
#7 486.0   Stored in directory: /root/.cache/pip/wheels/a9/92/74/7694cd5d3f10ea335ef507c10e877b2150de20975a986782b9
#7 486.0 Successfully built pyod scikit-learn combo matplotlib statsmodels suod psutil
#7 486.0 Failed to build numba llvmlite
#7 486.1 Installing collected packages: six, numpy, threadpoolctl, scipy, pytz, python-dateutil, pyparsing, pillow, llvmlite, kiwisolver, joblib, cycler, scikit-learn, psutil, patsy, pandas, numba, matplotlib, suod, statsmodels, combo, pyod
#7 489.8     Running setup.py install for llvmlite: started
#7 489.9     Running setup.py install for llvmlite: finished with status 'error'
#7 489.9     ERROR: Command errored out with exit status 1:
#7 489.9      command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-obn_7baq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/llvmlite
#7 489.9          cwd: /tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/
#7 489.9     Complete output (29 lines):
#7 489.9     running install
#7 489.9     running build
#7 489.9     got version from file /tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
#7 489.9     running build_ext
#7 489.9     /usr/local/bin/python /tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py
#7 489.9     LLVM version... Traceback (most recent call last):
#7 489.9       File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 105, in main_posix
#7 489.9         out = subprocess.check_output([llvm_config, '--version'])
#7 489.9       File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
#7 489.9         return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#7 489.9       File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
#7 489.9         with Popen(*popenargs, **kwargs) as process:
#7 489.9       File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
#7 489.9         self._execute_child(args, executable, preexec_fn, close_fds,
#7 489.9       File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
#7 489.9         raise child_exception_type(errno_num, err_msg, err_filename)
#7 489.9     FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
#7 489.9     
#7 489.9     During handling of the above exception, another exception occurred:
#7 489.9     
#7 489.9     Traceback (most recent call last):
#7 489.9       File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 191, in <module>
#7 489.9         main()
#7 489.9       File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 181, in main
#7 489.9         main_posix('linux', '.so')
#7 489.9       File "/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/ffi/build.py", line 107, in main_posix
#7 489.9         raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
#7 489.9     RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
#7 489.9     error: command '/usr/local/bin/python' failed with exit status 1
#7 489.9     ----------------------------------------
#7 489.9 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-64twn51n/llvmlite_6bacc08e1c51412680848201635b71b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-obn_7baq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/llvmlite Check the logs for full command output.
------
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1
</pre></code>

Here's the Docker container file:
<pre><code>FROM python:3.8
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
</pre></code>

Here's the requirements.txt file (only pyod required):
`pyod
`

**Comment by roachnt** [comment]
@tristantoupin Any update on this? I've had similar trouble. Looks like it has something to do with the `numba` dependency.

**Comment by roachnt** [comment]
Just figured it out. Need to conda install numba first:

`conda install numba`

**Comment by tristantoupin** [comment]
Sweet, I suspected it had to do with the installation in a container with the news M1 MacBooks since docker is a preview version.

@roachnt what's your machine?

**Comment by roachnt** [comment]
@tristantoupin So in my case I'm running docker on a TeamCity build pipeline, so slightly different use case it sounds like. But I was getting a similar error to you in a similar spot and figured numba had something to do with it.
