### ISSUE TITLE
ABOD error

### ISSUE THREAD

**Issue by learnerk** [yzhao062/pyod#290]
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function dot at 0x7fab0417f440>) found for signature:
 
 >>> dot(array(int64, 1d, C), array(int64, 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'dot': File: numba/core/typing/npydecl.py: Line 950.
    With argument(s): '(array(int64, 1d, C), array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: np.dot() only supported on float and complex arrays

def _wcos(curr_pt, a, b):  # pragma: no cover
    <source elided>
    wcos = np.dot(a_curr, b_curr) / (
            np.linalg.norm(a_curr, 2) ** 2) / (
            ^****

**Comment by philipproechner2** [comment]
Hi,

I have the same error using ABOD with PyOD. How did you solve this issue? Thanks.
