### ISSUE TITLE
How to decide which point is outlier and which inliner after model combination?

### ISSUE THREAD

**Issue by Okroshiashvili** [yzhao062/pyod#294]
I'm trying to combine `ROD` and `COPOD` model results using average and average of maximum and getting the results. After having this result, how do I decide whether the point is outlier or inliner? In other words, I need to have a threshold based on that I will mark the particular point as an outlier or inliner.

Edited:

I have unsupervised anomaly detection task and hence I have no labels

**Comment by yzhao062** [comment]
like all other models, the output is simple continuous scores. you could use the percentage, e.g., top 5%, as outliers. 

you can call utility function here to convert your scores to label by supplying a percentage. https://github.com/yzhao062/pyod/blob/3336c9dfe9ebaf7df685ac81316a4cb79d6abbd8/pyod/utils/utility.py#L175

**Comment by Okroshiashvili** [comment]
Thanks a lot @yzhao062 :)
