### ISSUE TITLE
Questions about outlier detection algorithms

### ISSUE THREAD

**Issue by pzn666** [yzhao062/pyod#311]
Hello

Thanks for your brilliant work! I am new for outlier detection domain and I have some questions.
Say I have some embeddings which embed informations from images and the dimension of these embeddings is around 1k to 4k (based on which feature extractor I choose). I wonder in high dimensional outlier detection domain, how "high" is the dimension that can still have some reliable algorithms? And if there are some reliable algorithms, which one is most recommended for the first try?

Any suggestions are appreciated, please help me :'(

**Comment by yzhao062** [comment]
For high-dimensional datasets, I would see go first with LODA, HBOS, COPOD, and iForest.
These four will be specifically suited for this case.

**Comment by pzn666** [comment]
Thanks!
