### ISSUE TITLE
BUG: PyTorch AutoEncoder NoneType Error when preprocessing=False

### ISSUE THREAD

**Issue by elisim** [yzhao062/pyod#313]
Hi,

When passing `preprocessing=False` to PyTorch AutoEncoder, the `self.mean, self.std` are not initialized, causing `__getitem__` throw an error.

problematic line:

https://github.com/yzhao062/pyod/blob/d9186d2eac4fcc9e04c245d3885ae06915cb56f5/pyod/models/auto_encoder_torch.py#L41

Thank you,
Eli

**Comment by yzhao062** [comment]
please use the tensorflow version for now. the pytorch version is under development yet. https://pyod.readthedocs.io/en/latest/_modules/pyod/models/auto_encoder.html

Thanks for the note though.

**Comment by elisim** [comment]
@yzhao062  I saw you solve this bug in the [latest release](https://github.com/yzhao062/pyod/releases/tag/V0.9.1), am I right? 🙂
