### ISSUE TITLE
 DeprecationWarning: `np.float` is a deprecated alias 

### ISSUE THREAD

**Issue by GBR-613** [yzhao062/pyod#319]
The following warnings appear with a couple of models, for example PCA:

```
c:\Programs\Python37\lib\site-packages\pyod\utils\utility.py:61: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if not isinstance(param, (numbers.Integral, np.integer, np.float)):
c:\Programs\Python37\lib\site-packages\pyod\utils\utility.py:65: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
```

I am using numpy 1.20.2, I believe it occurs with later versions as well.
There is no immediate impact (except of logs exploding), but it might cause issues some day. Appreciate if you could have a look in that.  
Probably the nearby np.integer should be replaced with "int" too.

**Comment by yzhao062** [comment]
Thanks for reporting this. I just updated the place with numpy.float and it should be in the next release.
I have not touched integers and they look fine for now according to the documentation (https://numpy.org/devdocs/user/basics.types.html).

Thanks again!
