### ISSUE TITLE
Partial_fit implementation

### ISSUE THREAD

**Issue by zabarah** [yzhao062/pyod#323]
is there an implementation for partial_fit in pyod models? How can I train multiple sub-sets incrementally?

**Comment by yzhao062** [comment]
Unfortunately, partial_fit is not implemented in PyOD yet...
outlier detection algorithms are generally hard to be done in this style. scikit-learn has no partial fit for outlier detection algorithms either (https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html , https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.LocalOutlierFactor.html)

**Comment by zabarah** [comment]
Is there any way to iteratively train the model

**Comment by yzhao062** [comment]
I think most outlier detection algorithms need global information. iterative training may be fine for selected algorithms, but you are assured most of them are not possible and costly.

**Comment by zabarah** [comment]
I understand. 

Thank you for all the work you have done. PYOD has helped many people.
