### ISSUE TITLE
COPOD Outlier Score

### ISSUE THREAD

**Issue by simonh115** [yzhao062/pyod#325]
Hey. Thanks for the great package. I have a question regarding the COPOD implementation. Your paper describes the algorithm as follows

![image](https://user-images.githubusercontent.com/43097359/127000778-5c9b7d8e-1bc8-431c-a8a8-d20c80f5f7b6.png)

while the code calculates max{p_s, (p_l, p_r)/2} (see snippet below).

`
self.O = np.maximum(self.U_skew, np.add(self.U_l, self.U_r) / 2)
`

Is this deviation from the paper on purpose? And is the code implementation the one that is conceptually correct?

**Comment by winstonll** [comment]
Hi Simon,

When the paper was written we used max{p_s, p_l, p_r}, then later we discovered empirically that max{p_s, (p_l + p_r)/2} worked slightly better so in the implementation we made a slight change.

Hope that answer the question.

**Comment by simonh115** [comment]
Hi, thanks a lot for the quick reply and clarification. Makes sense! :)
