### ISSUE TITLE
PyOD fails due to Sklearn version error

### ISSUE THREAD

**Issue by Haveon** [yzhao062/pyod#343]
PyOD is throwing an error with the newest version of sklearn (v1.0). It seems the PyOD code doing the check only looks at the minor revision number.

![image](https://user-images.githubusercontent.com/3052260/135658972-70f93b1c-7cbd-4439-b656-b60f02547fc8.png)

**Comment by yzhao062** [comment]
noted. working on a hot fix. thanks for reporting

**Comment by yzhao062** [comment]
fixed in v0.9.4

**Comment by Haveon** [comment]
Nice! I pulled from pypi and it's working now
![image](https://user-images.githubusercontent.com/3052260/135687425-cf9c7974-a79f-44a6-90e7-b7a58c6ed3e8.png)

Thanks!
