### ISSUE TITLE
Are the thresholds comparable for models run on the same data?

### ISSUE THREAD

**Issue by dcohron** [yzhao062/pyod#354]
I am trying to compare a number of unsupervised models on a given training dataset and am getting thresholds from ~1960 to -5.15e+38 with several in the -0.03 range.  Are the thresholds meant to be comparable?  Are the better models those with thresholds closer to zero?  Is there meaning in the negative numbers?  Is there a better way to compare unsupervised model results?

Thank you much.

**Comment by yzhao062** [comment]
for different algorithms, the scores have different meanings...So basically the lower scores means more normality, while higher scores denotes more outlyingness. Note, you could directly compare the scores from different scores directly. However, if you really need to do this, please scale the scores into [0,1] first for all algorithms.
