### ISSUE TITLE
ValueError: Sklearn version error

### ISSUE THREAD

**Issue by hanzigs** [yzhao062/pyod#357]
Hi,
getting "ValueError: Sklearn version error" for "from pyod.models.iforest import IForest"

But this is first time, until last Friday this was working fine, may I know the issue please.

Having following versions
```
scikit-learn==0.24.2
pyod==0.8.9
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\PP\\ADtils.py in <module>
----> 21 from pyod.models.iforest import IForest #Isolation Forest

~\anaconda3\envs\adpy\lib\site-packages\pyod\models\iforest.py in <module>
     12 from sklearn.utils import check_array
     13 
---> 14 from .base import BaseDetector
     15 from ..utils.utility import invert_order
     16 # noinspection PyProtectedMember

~\anaconda3\envs\adpy\lib\site-packages\pyod\models\base.py in <module>
     13 from ..utils.utility import _get_sklearn_version
     14 
---> 15 if _get_sklearn_version() > 20:
     16     from inspect import signature
     17 else:

~\anaconda3\envs\adpy\lib\site-packages\pyod\utils\utility.py in _get_sklearn_version()
    444     if int(sklearn_version.split(".")[1]) < 19 or int(
    445             sklearn_version.split(".")[1]) > 24:
--> 446         raise ValueError("Sklearn version error")
    447 
    448     return int(sklearn_version.split(".")[1])

ValueError: Sklearn version error
```

**Comment by yzhao062** [comment]
I guess the best way is to update PyOD...for instance 0.9.4 or 0.9.5
We rewrite the sklearn dependency check all together

pip install pyod==0.9.5 should be the easiest fix

**Comment by hanzigs** [comment]
Yeah, That worked, Great, Thanks

**Comment by hanzigs** [comment]
@yzhao062 
My previous deployed models got affected, May I know why it is please, Thanks

**Comment by yzhao062** [comment]
My best guess is sklearn got updated in your environment. 
![image](https://user-images.githubusercontent.com/15079146/140666200-bb96dd32-bc98-4996-8425-32b527e1fa84.png)

Its version no longer follows the 0.2x logic. so our check fails.

**Comment by hanzigs** [comment]
Thanks for that, I agree to the point
