### ISSUE TITLE
Unexpected results in MAD when predicting

### ISSUE THREAD

**Issue by Quentin62** [yzhao062/pyod#358]
In the `_mad` function, the decision score is computed with:
https://github.com/yzhao062/pyod/blob/master/pyod/models/mad.py#L129-L130

``` python 
diff = np.abs(obs - self.median)
return np.nan_to_num(np.ravel(0.6745 * diff / np.median(diff)))
```
This function is used for both fit and predict.
Here, the denominator is the median of the difference between the given observations and the median. 
The problem is that in the case of a prediction `np.median(diff)` uses the current observations and not the ones used for fitting and this can leads to wrong score.
For example, if you use `decision_function` with one observation, the output score will always be 0.6745 because in this case diff == np.median(diff).

``` python
from pyod.models.mad import MAD
import numpy as np

mod = MAD(threshold=3)
x = np.random.normal(size=100).reshape(-1, 1)
mod.fit(x)
mod.median
y = np.array([[1000]])  # obviously an anomaly
mod.decision_function(y)  # array([0.6745])
mod.predict(y)  # array([0])
```

Idea to solve the problem:
Saving the fitted median diff in the sae way the median is saved:

``` python 
diff = np.abs(obs - self.median)
self.mediandiff = np.median(diff) if self.mediandiff  is None else self.mediandiff
return np.nan_to_num(np.ravel(0.6745 * diff / self.mediandiff))
```

**Comment by John-Almardeny** [comment]
Which `PyOD` version are you using?
Because this bug has been fixed in the latest version.

**Comment by Quentin62** [comment]
I use PyOD 0.9.5

**Comment by John-Almardeny** [comment]
Okay. I double-read your query and I understand it now.

Yes, you are right. Please feel free to open a `PR`.

Thanks.

**Comment by yzhao062** [comment]
Thanks for doing this! It is in the latest version!
