### ISSUE TITLE
Allow NaN and Infinity values in MAD

### ISSUE THREAD

**Issue by ingonader** [yzhao062/pyod#376]
Allow `np.NaN` and `np.infty` values in the MAD outlier detection method. The method as implemented seemes to have some functionality to deal with `NaN`s (using `np.nanmedian()` at least in some calculations), but the `check_array()` function, as currently parametrized, throws an error.

It would be great if the corresponding function calls could be reparametrized (with `force_all_finite=False`) and also the calculation of `self.median_diff` in `_mad()` would be done via `np.nanmedian()`.

**Comment by yzhao062** [comment]
this is merged and closed. thanks for the contribution.
