### ISSUE TITLE
Bias in DeepSVDD

### ISSUE THREAD

**Issue by psorus** [yzhao062/pyod#385]
If you read Lukas Ruffs Paper ([https://ls9-www.cs.tu-dortmund.de/publications/ICML2018.pdf](https://ls9-www.cs.tu-dortmund.de/publications/ICML2018.pdf) )
he writes in 3.3 Proposition 2 that "Proposition 2 implies that networks with bias terms can easily learn any constant function" and thus suggests not using a bias term in the definition of a DeepSVDD paper.
Also, his code ([https://github.com/lukasruff/Deep-SVDD-PyTorch/blob/1901612d595e23675fb75c4ebb563dd0ffebc21e/src/networks/mnist_LeNet.py#L16](https://github.com/lukasruff/Deep-SVDD-PyTorch/blob/1901612d595e23675fb75c4ebb563dd0ffebc21e/src/networks/mnist_LeNet.py#L16) ) disables these bias terms.
Is there any reason I am not aware of why pyod's version of deep svdd uses biases in its network definition?

**Comment by yzhao062** [comment]
Great catch. Should be fixed in the next release
