### ISSUE TITLE
MO_GAAL 'stop_epochs' parameter not working?

### ISSUE THREAD

**Issue by anirbanmukherjee2709** [yzhao062/pyod#386]
Hi 

I have been running MO_GAAL for unsupervised anomaly detection. Even though I have set the 'stop_epochs' parameter to 20. I am getting 60 epochs run regardless

Parameter setup and class instantiation:
![image](https://user-images.githubusercontent.com/83485974/162566977-3abddc3e-3bba-4dea-ade4-1a58da591eda.png)

While running: 
![image](https://user-images.githubusercontent.com/83485974/162567000-f8de8a43-21ad-48b1-ac01-1e40fd842142.png)

as you can see in the above images.
Please let me know if I am missing anything inadvertently. Thanks in advance.

**Comment by yzhao062** [comment]
In the code, it is set as 
![image](https://user-images.githubusercontent.com/15079146/162587322-862f6bb7-e9ef-4acd-bb9d-eae8ef60df0b.png)

I do not recall why the epochs = 3 x stop_epochs, but it is from the author's repo:

https://github.com/leibinghe/GAAL-based-outlier-detection/blob/master/SO-GAAL.py

![image](https://user-images.githubusercontent.com/15079146/162587346-d340ed7a-5d4d-4e81-94e4-d22aa1c9d943.png)

if you really want to run 20 epochs in total, maybe set this equal to 7
