### ISSUE TITLE
Is it possible to install pyod without numba?

### ISSUE THREAD

**Issue by wizard1359** [yzhao062/pyod#404]
Hello,

I am facing using regarding numpy,we are only allowed to use the versions of numpy>1.22,however the latest version and most of the versions of  numba only supports the numpy versions < 1.22,hence is it possible to use pyod without numba?,please suggest me a workaround if possible.Thanks.

**Comment by yzhao062** [comment]
Models are all here: https://github.com/yzhao062/pyod/tree/master/pyod/models

![image](https://user-images.githubusercontent.com/15079146/166724685-95860370-4ee0-4ab4-a2d0-e2163234fe52.png)

if one depends on numba, you will see that in the import on the top.

**Comment by wizard1359** [comment]
I got it,Thank you so much!!!
