### ISSUE TITLE
generate_data from data.py causes warning with default flags because of parameter deprecation that never happened

### ISSUE THREAD

**Issue by rkost** [yzhao062/pyod#409]
I am new to this project but haven't found a related issue.

`data.py` provides the function `generate_data`:

https://github.com/yzhao062/pyod/blob/bb3a14ea4df149e3773fa34116dfc62e1c8d5c89/pyod/utils/data.py#L112-L114

The parameter `behavior` is set to `old` by default which causes a warning to be displayed, notifying about this behavior getting deprecated in version `0.9.0`. 

The 'fix' would be to call the function with `behavior='new'` as it would not warn you about anything, however the documentation states, that the parameter will be removed altogether in `0.9.0`. I guess that never happened since we are now on `1.0.1`?

https://github.com/yzhao062/pyod/blob/bb3a14ea4df149e3773fa34116dfc62e1c8d5c89/pyod/utils/data.py#L142-L155

Can we just move on and either remove that parameter now or un-deprecate it, if it is that important? We would need to go through all examples and tests and change the order of the expected return values, right? I would happily do that so that I can rely on this python package.

I also wondered why the tests would not fail when there are warnings?

**Comment by yzhao062** [comment]
That is right. I will remove the warning in the next release.
