### ISSUE TITLE
Meaning of Contamination in SUOD

### ISSUE THREAD

**Issue by madarax64** [yzhao062/pyod#416]
Hello,
Thanks for the excellent work with PyOD! I am using SUOD to create an ensemble of 6 models (3 ABOD, 3 INNE). Each of these instances has their own (different) contamination value. However, the SUOD object itself has a separate contamination parameter. What is the effect of/interaction between the contamination parameter on the SUOD object and the constituent outlier detectors (which could have their own individual contamination settings)?

On a side note, it is my understanding that each of these 6 models learns (in) a different subspace, since (different) random projections are used per instance. Is this correct?
Thanks!

**Comment by yzhao062** [comment]
Oh I think the SUOD contamination override the base models'. But to be assured that contamination is not an important factor but only for converting outlier scores to labels.

Yes. Random projection will be different among detectors. If the same should be used, you may consider turnoff the projection function.

**Comment by madarax64** [comment]
Hello @yzhao062 ,
Thanks alot for the speedy response! In my case, I directly use the predict() function to obtain labels i.e. I don't use the raw scores, so there's a chance it could significantly affect my results and their reporting. Is there a way I could fully confirm the overriding behavior?

Thanks, got it!

**Comment by yzhao062** [comment]
you can try to manually verify this by accessing each base estimator
![image](https://user-images.githubusercontent.com/15079146/175381642-f64fd6da-484d-4a3d-890e-2dbd670a5d10.png)

then you could quickly check if the returned results from base detectors are different, e.g., the number of 1 and 0.

But likely we should use the same contamination for all detectors, since that is how you assume the percentage of outliers.

**Comment by madarax64** [comment]
Hello @yzhao062 ,
Thanks for the response. I wasn't very clear on your example above, but it inspired me to try something similar: Fixing the SUOD contamination, I set the contamination of the constituent ODs to very high values. The performance of the SUOD model did not change. But when I changed the contamination of the SUOD object itself, then the performance changed. This suggests that (as you said earlier) the SUOD contamination is actually the active setting, not the contamination of the constituents. Do you think this was a good/suitable methodology to check this?

**Comment by yzhao062** [comment]
to my knowledge that is fair...and I do not have better suggestion for now :)

**Comment by madarax64** [comment]
Hello @yzhao062 ,
Haha, that's fine for me. Thanks for all the help!
