### ISSUE TITLE
Is it possible to make CBLOF ignore contamination parameter?

### ISSUE THREAD

**Issue by marchezinixd** [yzhao062/pyod#42]
CBLOF parameters are useless. Basically the only thing that matters when dealing with the method is the contamination parameter, if i set it to 0.3 it will find 30% of anomalies and it doesn't matter how normal they are or if they belong to a big cluster. For what i understood about the method it has the ability to define what is an anomaly and what is not only based on the parameters alpha and beta, why is this happening?
Is there a way to ignore contamination?

**Comment by yzhao062** [comment]
Hi there,

contamination is just a universal parameter across all detection algorithms. what it is doing is to simply rank all points by raw outlier scores and then mark the top %contamination into outliers. 

If you want to do this manually, I would suggest using decision_function instead to get the raw score. 

For instance, for a fitted model, decision_function(X_test) returns [0.1, 0.8, 0.3, 0.2, 0.2]. If you are using predict(X_test) with contamination==0.2, then you will receive [0,1,0,0,0]. So predict() is simply a wrapper on decision_function().

Let me know if this is clear:)
Thanks,
Yue

**Comment by marchezinixd** [comment]
Thank you very much, I just tested it and it worked for me.
