### ISSUE TITLE
Attributes written on the docs don't exist - very annoying.

### ISSUE THREAD

**Issue by BexTuychiev** [yzhao062/pyod#439]
Attributes written in the docs don't exist. For example, after training an `IForest` instance, I wanted to see the `labels_` attribute, which isn't accessible:

```python
from pyod.models.iforest import IsolationForest

iforest = IsolationForest().fit(df)
iforest.labels_
```
```python
AttributeError: 'IsolationForest' object has no attribute 'labels_'
```

The same is true for many labels given in the docs, including `decision_scores_`, `threshold_` `feature_importnaces_`, etc.

While the docs suggest I use the `labels_` attribute instead of `fit_predict`. I am using the latest version of the library, 1.0.4.

Can anybody help?

**Comment by yzhao062** [comment]
I suspect it is due to the API usage.
Maybe change to


```
iforest = IsolationForest()
iforest.fit(df)
iforest.labels_
```

You can follow the example here
https://github.com/yzhao062/pyod/blob/master/examples/iforest_example.py

**Comment by BexTuychiev** [comment]
It is the same result. This issue also happens with LOF and I think I know why - both are wrappers around Scikit-learn's estimators. But I went through the source code but couldn't find anything wrong. 

I really need this solved as I am a DataCamp instructor and doing a course on anomaly detection, which uses PyOD a lot. This is an excellent opportunity to brand the package as the leading library for anomaly detection but small issues like this and inattentive discrepancies with the code and the docs would really embarrass me, @yzhao062

**Comment by yzhao062** [comment]
the example runs fine honestly...

![image](https://user-images.githubusercontent.com/15079146/190201305-098331af-3b9b-4d92-b809-0d03c0b35c9a.png)

could you provide something for reproducibility?

**Comment by yzhao062** [comment]
Oh I see the problem,

you should 

from pyod.models.iforest import IForest

Otherwise you import the scikit-learn version

**Comment by yzhao062** [comment]
similarly, from pyod.models.lof import LOF
