### ISSUE TITLE
Contamination parameter during fit?

### ISSUE THREAD

**Issue by filipporemonato** [yzhao062/pyod#456]
I am having trouble understand how the contamination parameter works.
In the beginning, my question was exactly the same as the one in this issue https://github.com/yzhao062/pyod/issues/144. After reading the (very useful) reply, I was left with the understanding that the contamination parameter was used only during the prediction/classification step to decide the threshold, but then I noticed that contamination is actually a parameter of the **constructor** of all algorithms.
In addition, the docstring (for instance for KDE) reads "The amount of contamination of the data set, i.e. the proportion of outliers in the data set. **Used when fitting** to define the threshold on the decision function." which makes it unclear how it's actually being used (since the threshold should not be defined during fitting, but only after scoring all samples, i.e. at the prediction/classification step).

So, is the contamination actively used during fitting?
If yes, why? And how?

**Comment by andrewm4894** [comment]
The idea is to minnmax normalize based on the largest distance or raw anomaly score observed in the training data. That way you can then sort of think of a contamination param of 1% as setting the threshold at the of the most strange 1% of observed training data. 

So it needs to know what was the biggest raw anomaly score during training to give you a nice anomaly score that feels like a percent at prediction time since it's normalized based on the distribution (sort of) of raw anomaly scores seen during training.

**Comment by andrewm4894** [comment]
Cell 8 in this notebook explains how I think of it (and how we use it, I think similar to in pyod).

https://github.com/netdata/netdata/blob/master/ml/notebooks/netdata_anomaly_detection_deepdive.ipynb

**Comment by filipporemonato** [comment]
> The idea is to minnmax normalize based on the largest distance or raw anomaly score observed in the training data. That way you can then sort of think of a contamination param of 1% as setting the threshold at the of the most strange 1% of observed training data.

Hei, thanks for the contribution! It's an good idea to normalise respect to the anomaly scores, so that the final prediction is sort of a percent. My problem here is that I don't think this should be done respect to the **training data**, in the fit step.
In anomaly detection, training is almost always done on confirmed normal data (that's how, e.g., autoencoders are trained). Once the model has learned what a normal situation is, it is then used on contaminated data to flag the anomalies.
As such, the contamination value of the training data should always be 0 (which is not an allowed value in PYOD).
One could give an estimate of how much contamination one can expect in the **test** data, but the training data is very often clean.
That's why I don't understand why the contamination parameter is given in the constructor, and _IF_ it's used during fitting, why.

I am exactly in this situation, where my train data is guaranteed without anomalies, so I have 0 contamination. It's the test data that I need to analyse to flag anomalies there.

**Comment by yzhao062** [comment]
I personally think contamination is not important. You can set it to any value below 0.5.
It is only used in the prediction of binary labels. It is nothing but binarize the raw outlier scores (which has nothing to do with contamination).

For instance, if the predicted outlier scores by decision_function is [0.1, 0.2, 0.3, 0.4, 0.5], and contamination =0.2. then [0,0,0,01]. contamination does not affect [0.1, 0.2, 0.3, 0.4, 0.5]

**Comment by filipporemonato** [comment]
Hey @yzhao062, thanks for the reply.
Yes, that's what I understood reading your reply to the other issue, but I was just confused by the docstring and the fact that contamination is part of the constructor of the class.
Thanks for the clarification!
