### ISSUE TITLE
Ensemble methods integration in scikit learn pipeline

### ISSUE THREAD

**Issue by Paroag** [yzhao062/pyod#498]
Hello,

I have been using this great package for the last months and I have to say that I find it very intuitive and developer friendly. Great work !

I often work with scikit learn pipelines, and have integrated pyod's model to my pipeline very easily. I want to switch to a more ensemblist approach, mainly using the function from `pyod.models.combination` to combine the output of different algorithms in my pipeline.

I've not yet find an elegant way to do so, as the combination function from pyod are functions and not classes.

I'm looking for something like:
```
Pipeline([
    ("scaler", StandardScaler()),
    (
        "composite_detector",
        CompositeDetector(
            [
                IForest(),
                CBLOF(),
                COPOD(),
                ECOD(),
            ],
            combination_method=average,
            contamination=contamination,
        )
    ),
])
```

My question is: Is there a way to do so currently ?

I have developed my own ensemblist estimator (CompositeEstimator) that may use an arbitrary number of underlying estimators and a combination function (matching the same signature as pyod's combination functions) to provide my scoring. If no better solution is currently available, I'm interested in contributing to pyod by standardizing this estimator and integrating it following your development standards.

Thanks for the help !

**Comment by yzhao062** [comment]
here is one example for doing so: https://github.com/yzhao062/combo/blob/master/examples/detector_comb_example.py

**Comment by Paroag** [comment]
This is exactly what I'm looking for. I should have asked sooner. Thanks !
