### ISSUE TITLE
Documentation / Implementation difference in Autoencoder

### ISSUE THREAD

**Issue by Maddosaurus** [yzhao062/pyod#50]
While exploring the AutoEncoder in pyod, I've noticed a discrepancy between the generated docs and the implementation.  
While the docs (https://pyod.readthedocs.io/en/latest/pyod.models.html#module-pyod.models.auto_encoder) inform you, that __hidden_neurons__ defaults to a list ([64, 32, 32, 64]), the implementation assigns *None* as type: https://github.com/yzhao062/pyod/blob/development/pyod/models/auto_encoder.py#L126  
Whilst this isn't a problem for itself, instancing an AutoEncoder like that resulted in a TypeError on my side: 
```
         # Verify the network design is valid
>       if not self.hidden_neurons == self.hidden_neurons[::-1]:
E       TypeError: 'NoneType' object is not subscriptable
```

It might be worth a try to change the default for __hidden_neurons__ to the list mentioned in the docs.  
And by the way: Thanks for this framework, it is really a breeze to work with!

**Comment by Maddosaurus** [comment]
Adhering to best practices seems the way to go here.  
Seems I overlooked the default init for the param lateron in the function. Closing as not relevant

**Comment by yzhao062** [comment]
@Maddosaurus Thanks for checking. Please let us know if you find anything else worth investigating:)
