### ISSUE TITLE
Does pydo support regression tasks?

### ISSUE THREAD

**Issue by Bjoux2** [yzhao062/pyod#52]
```
from pyod.models.xgbod import XGBOD

xgb = XGBOD()

print(y[0:10])

xgb.fit(X,y)
```

![image](https://user-images.githubusercontent.com/12781926/51423790-1cc8a500-1c00-11e9-9b4a-081bc2a6ebae.png)

Thanks!

**Comment by yzhao062** [comment]
Hi Ming,

XGBOD is a supervised outlier detection algorithm, instead of a regressor:)
y should be binary: 0 stands for inliers and 1 stands for outliers.

Thanks,
Yue
