### ISSUE TITLE
issues about scikit-learn

### ISSUE THREAD

**Issue by celestinoxp** [yzhao062/pyod#542]
1- in requirements.txt you have "scikit_learn" i think should scikit-learn. should change underscore "_" to hiffen "-".
2 - pyod is a indepencence of pycaret, i'm tryng making support to scikit-learn 1.4, but pyod have a conflict, please make support to scikit-learn 1.4 and release a new version

thanks

**Comment by celestinoxp** [comment]
@yzhao062

**Comment by yzhao062** [comment]
Thanks for pointing this out. wiredly I did not notice this for six years and it is still working.

Some recent updates are made to pyod 1.1.3 to make it compatible with scikit-learn 1.4 -- all the tests are now passed with scikit-learn 1.4 (https://github.com/yzhao062/pyod/actions)

**Comment by celestinoxp** [comment]
> Thanks for pointing this out. wiredly I did not notice this for six years and it is still working.
> 
> Some recent updates are made to pyod 1.1.3 to make it compatible with scikit-learn 1.4 -- all the tests are now passed with scikit-learn 1.4 (https://github.com/yzhao062/pyod/actions)

thanks for the new version.
I honestly don't know why there was no error when using underscore instead of hyffen... strange...
Interestingly I discovered some errors in my pycaret pr, so now it seems that everything has improved... thank you
