### ISSUE TITLE
Resource updation request of an Article - Outlier Detection using PyOD 

### ISSUE THREAD

**Issue by lakshay-arora** [yzhao062/pyod#56]
Hi, 
I have written an article on Outlier Detection using PyOD on Analytics Vidhya Blog -
[https://www.analyticsvidhya.com/blog/2019/02/outlier-detection-python-pyod/](https://www.analyticsvidhya.com/blog/2019/02/outlier-detection-python-pyod/) 

In the article, I have tried to explain the need for outlier detection and how can we use pyod for the same and also implemented pyod on a real world data set.  
Please consider it including in your resources section on GitHub. I believe it would be really helpful for the people who wanted to get started with pyod.

Thanks

**Comment by yzhao062** [comment]
Hey Lakshay,

Thanks for writing such a good post. I have added your tutorial article to "[quick start](https://github.com/yzhao062/pyod#quick-start-for-outlier-detection)" on readme and "[featured post](https://pyod.readthedocs.io/en/latest/about.html)", which feels more relevant:)

Thanks again.
Yue

**Comment by lakshay-arora** [comment]
Thanks, @yzhao062
