### ISSUE TITLE
n_jobs ignored

### ISSUE THREAD

**Issue by cibic89** [yzhao062/pyod#58]
Hi, I'm using xgbod with n_jobs = -1 and its no different than using it with n_jobs = 1...

**Comment by yzhao062** [comment]
n_jobs specify the number of threads to run in parallel...I guess you would like to compare n_jobs=1 to n_jobs=2 or 3?

**Comment by cibic89** [comment]
I would like to run XGBOD much faster as currently it only uses one thread...

**Comment by yzhao062** [comment]
Sorry, I lost this thread. 

Most of the models follows "If -1, then the number of jobs is set to the number of cores.". However, XGBOD actually depends on xgboost API and I am not sure whether xgboost is implemented this way. I would suggest using n_jobs=2, 3, or 4 to see whether the performance improves.

One thing to add is XGBOD also relies on various unsupervised models to extract feature representations, which can be time-consuming. These unsupervised models are not enabled with parallelization. So multi-core may not lead to a significant improvement in this case.

Sorry for the delay.
Yue

**Comment by cibic89** [comment]
Hi,

Tried n_jobs from 1 to 16 and there is no difference.

You are probably right about the unsupervised algorithms.
________________________________

**Comment by yzhao062** [comment]
Agreed. Will think about how to speed it up for practical use.
Thanks for reporting this:)
