### ISSUE TITLE
Breadth-First Approach in FeatureBagging 

### ISSUE THREAD

**Issue by marcelflygare** [yzhao062/pyod#59]
May I ask a question about the implemented approach for "combination" in the "feature_bagging.py" ?

IMHO, the idea of using "maximization" is not a precise reflection of the original paper (`lazarevic2005feature`).  The authors describes there a breath-first search procedure; arguably the numeric differences might be small. 
However, please consider a generic toys example as a counter-example:

` |------| Alg1| Alg2|`
`| Obs1  | 10.0| 2.0   |`
`| Obs2  | 9.0  | 3.0   | `
`| Obs3  | 8.0  | 4.0   |`

Maximization would return the order Obs1 (score:10) , Obs2(score:9), Obs(score:3), Breadth-First Search would return Obs1 (rank1 in Alg 1), Obs3, (rank1 in Alg 2) and the Obs2. 

Many thanks.

**Comment by yzhao062** [comment]
Hi there,

Thanks for the note. It is true that the current implementation of the combination is slightly different from the original paper (at least not the original bfs which is the aggregation of rankings). 

The rationale behind the current design is more practical: cumulative sum (averaging) usually yields more stable results [1]. Indeed, most of the dector combination methods often lead to similar results. So I simply take the ones in [combination models](https://github.com/yzhao062/pyod/blob/master/pyod/models/combination.py) Feature Bagging for saving time.

I will add this into the TODO list, and you are also welcome to implement it if you are interested:)

Yue

----

[1] Lu, S., Liu, L., Li, J. and Le, T.D., 2018, December. Effective Outlier Detection based on Bayesian Network and Proximity. In 2018 _IEEE International Conference on Big Data (Big Data)_ (pp. 134-139). IEEE.

**Comment by marcelflygare** [comment]
Many thanks for adding it to the ToDo list; agreeing completely with your explanation. (Unfortunately, I might be short of time to contribute; sorry )

**Comment by yzhao062** [comment]
Documented in https://github.com/yzhao062/pyod/commit/fcdf9c9b47c85b3de89e91c9a9eb3778cd69d583
