### ISSUE TITLE
Generate Synthetic Data in Clusters

### ISSUE THREAD

**Issue by John-Almardeny** [yzhao062/pyod#65]
Adding new feature - that is generate artificial data in clusters.
Creating utility function to generate synthesized data in clusters.
Generated data can involve the low density pattern problem and global outliers which are considered as **difficult tasks** for outliers detection algorithms.
[Highlights](http://www.cs.cuhk.hk/~adafu/Pub/pakdd02.pdf)

**Comment by yzhao062** [comment]
Did some clean-up and refactored the code for consistency. The function is now released. Thanks for the work. Closed by #84. Available in the latest version ([v0.7.0](https://pypi.org/project/pyod/)).
