### ISSUE TITLE
Auto encoder input layer neurons

### ISSUE THREAD

**Issue by Tsinghua-gongjing** [yzhao062/pyod#87]
Hi, thank you for the great module.

For the auto encoder part, it seems that a input layer with number of neurons same as features is defined. However, the same is also next defined as the first hidden layer. Is this often the case? Does the model will be too complex for data set with large number of features (e.g. 10000)?

Thanks,
Jing

**Comment by yzhao062** [comment]
Hi there, 

I am a bit confused about your first question. You should not worry about the number of input feature space. For instance, your input is a [20000, 10000] matrix (20,000 samples with 10000 features), you could define hidden_neurons = [1024, 512, 64, 32, 32, 64, 512, 1024] or hidden_neurons = [2000, 1000, 500, 500, 1000, 2000]. All up to you. To be honest, it does not need to be symmetrical.

Let me know whether this makes sense.

**Comment by Tsinghua-gongjing** [comment]
Thank you for the reply.

For my case, the hidden_neurons is default ([64, 32, 32, 64]) and input has 19743 features. The model by default has 7 layers in total and the first two are related to feature numbers. I'm not sure if the first two layer is often necessary in auto encoder or just one layer is enough? The parameters is too large thus raise Resource exhausted error on my GPU server (8G memory).

![model_summary](https://user-images.githubusercontent.com/12371558/57343459-0ece6e00-7176-11e9-8088-b48884d23861.png)

**Comment by yzhao062** [comment]
I do not think that is necessary. Is there any way on your end to skip the second layer?

**Comment by Tsinghua-gongjing** [comment]
I tried to edit the additional layer building part of auto_encoder.py script. Looping hidden_neurons_ from index 1 seems can skip the second layer.

Before:

       # Additional layers
        for i, hidden_neurons in enumerate(self.hidden_neurons_, 1):
            model.add(Dense(
                hidden_neurons,
                activation=self.hidden_activation,
                activity_regularizer=l2(self.l2_regularizer)))
            model.add(Dropout(self.dropout_rate))

After: 


        # Additional layers
        for i, hidden_neurons in enumerate(self.hidden_neurons_[1:], 1):
            model.add(Dense(
                hidden_neurons,
                activation=self.hidden_activation,
                activity_regularizer=l2(self.l2_regularizer)))
            model.add(Dropout(self.dropout_rate))`

**Comment by yzhao062** [comment]
perfect. as long as it could compile. It does not require symmetry so you are welcome to use the customized number of neurons, just FYI.

**Comment by Tsinghua-gongjing** [comment]
Thanks for the effort. By the way, why the neural network based methods are not benchmarked/compared in your doc?

**Comment by yzhao062** [comment]
The main reason is the benchmark is mainly on UCI datasets (which are too small for nn). May build some benchmark for nn in the future with large datasets. Feel free to suggest some :)
