### ISSUE TITLE
Why OCSVM is regarded as linear model?

### ISSUE THREAD

**Issue by RockLeeStudio** [yzhao062/pyod#90]
OCSVM  is regarded as linear model, but the decision function learned by  OCSVM  is a not-linear curve.

**Comment by yzhao062** [comment]
Hi there,

Do not worry about the category. It is more for educational purpose only. I used the same category as http://charuaggarwal.net/outlierbook.pdf (see screenshot)

![image](https://user-images.githubusercontent.com/15079146/57533343-8681d180-730b-11e9-9b51-b9e54c4344a4.png)

The definition of "linear" here is not about decision boundaries (Outlier Analysis 2ed page 65):
![image](https://user-images.githubusercontent.com/15079146/57533402-afa26200-730b-11e9-945b-7347799d597e.png)

**Comment by RockLeeStudio** [comment]
It's very clear. Thanks for you reply.
