### ISSUE TITLE
Code inconsistency

### ISSUE THREAD

**Issue by lachhebo** [yzhao062/pyod#91]
Hello, 

In the documentation of knn, it is said that : we can choose an algorithm between BallTree, KDTree ,brute-force and auto. 

However, The Ball Tree structure is always applied with  `decision_function() `: 

If we train a knn with X_train and the algorithm parameter set to KDTree : 

It will evaluate decision_score on X_test with a Ball Tree. 

Could you modify the code to allow the use of KDTree or brut-force on the testing dataset.

**Comment by yzhao062** [comment]
Thanks for spotting this. This inconsistency is caused by fixing #23 . 
We now force the kNN model to use ball tree to be compatible with more distance metrics. I will update the documentation (and code) soon.

Thanks again.
Yue

**Comment by lachhebo** [comment]
By the way, the radius parameter is also not used with the Ball Tree : 
I think it can be easily fixed by using the function `query_radius() ` 
instead of  `query` in the `decision_function `.
