### ISSUE TITLE
code error of small large cluster definition in CBLOF

### ISSUE THREAD

**Issue by shangwen777** [yzhao062/pyod#94]
for i in range(1, self.n_clusters_):

            temp_sum = np.sum(size_clusters[sorted_cluster_indices[-1 * i:]])
            if temp_sum >= n_samples * self.alpha:
                alpha_list.append(i)

            if size_clusters[sorted_cluster_indices[i]] / size_clusters[
                sorted_cluster_indices[i - 1]] >= self.beta:
                beta_list.append(i)

Since the temp_sum started from the largest cluster, in the first iteration, if the largest cluster not bigger or equal to 90% of the total sample size, then the largest cluster will not be in the alpha_list, this should not be true according to the original paper. beta_list has the similar issue.

**Comment by shangwen777** [comment]
Here I referred the code in cblof algorithm.

**Comment by yzhao062** [comment]
Hi. Thanks for reporting this and PR #95 ...I did not fully get what is the bug but did some quick tests:

**Test1 (cblof_example.py)**:
With the original code:
![image](https://user-images.githubusercontent.com/15079146/57585157-41e46a80-74b2-11e9-9e56-0d5fc9bf6452.png)

After modification:
![image](https://user-images.githubusercontent.com/15079146/57585073-f7aeb980-74b0-11e9-830b-20e5acfebe7c.png)

**Test2 (temp_do_not_use.py on cardio.mat)**:
With the original code:
![image](https://user-images.githubusercontent.com/15079146/57585149-29745000-74b2-11e9-8ff1-f66fc848ed76.png)

After modification:
![image](https://user-images.githubusercontent.com/15079146/57585179-7fe18e80-74b2-11e9-8ed8-663b58f83c0e.png)

To reproduce test2, you need cardio.mat file and temp_do_not_use.py (they can be downloaed [here](http://www.andrew.cmu.edu/user/yuezhao2/shared/pyod_test.zip)):
![image](https://user-images.githubusercontent.com/15079146/57585202-c46d2a00-74b2-11e9-8f71-373964fe7489.png)

As you could see the fix does not necessarily improve the performance (this is not comprehensive but a sample test only), I will need to do more reading to understand what is the problem. Stay tuned :)

**Comment by shangwen777** [comment]
Hi, 

Thanks for your quick response! I'd love to discuss with you. From the performance you tested, it doesn't improve. I am trying it with unsupervised data, so I did not know the model's performance.
But, I can explain the theoretical definition from my understanding.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/19768560/57592313-a4158d80-74fb-11e9-8d5b-97e93647b50d.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/19768560/57592340-cc9d8780-74fb-11e9-8935-51d9fa16d21a.png">

These pictures are the original quote from "Discovering Cluster Based Local Outliers". So, I think based on formula one, the large cluster should be the minimal sets of clusters in descending sequence, whose total size is larger or equal to say 90% of the whole sample size.

For example, I have 8 clusters:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/19768560/57592526-c1972700-74fc-11e9-9316-15da16de46ab.png">

Actually, the large cluster size should include [270, 437, 577, 614, 689, 746], because their sum is 3333 which is bigger than 3199.5 = 3555 * 0.9.  If the index of the ascending cluster size array [30, 192, 270, 437, 577, 614, 689, 746] is [0, 1, 2, 3, 4, 5, 6, 7], then the alpha_list index should be [2, 3, 4, 5, 6, 7]. But by using your code, the alpha_list is [6, 7].
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/19768560/57592950-deccf500-74fe-11e9-8e5f-8eaa7e43f52e.png">

**Comment by yzhao062** [comment]
Cool. thanks for the content. will take another a look at the paper and the code as I implemented months ago and the memory is not fresh. will report back here.

**Comment by yzhao062** [comment]
You are correct. Just did some test.
![image](https://user-images.githubusercontent.com/15079146/59380028-2923da80-8d26-11e9-84ae-b6b643838a5b.png)
This is the result on cardio.mat with n_clusters == 8,
You could see cluster sizes are [135, 176, 263, 62, 4, 15, **283**, 160] and the indices of the clusters in ascending order (smallest to the largest) is [4, 5, 3, 0, 7, 1, 2, 6]. So **cluster 6** is the largest one with the size equal to **283**.

Running the current algorithm, alpha list is [5,6,7] and beta_list is empty. This suggests the sum of largest 5 clusters exceeds the total number * alpha (which is 0.9). 283+263+176+160+135 > 1089*0.9.
![image](https://user-images.githubusercontent.com/15079146/59380435-1bbb2000-8d27-11e9-8fdb-1db2ed758b44.png)

So you are right! the correct large_cluster_labels should be [1, 2, 6, 7, 0] instead of [1, 2, 6].

I just merged your PR... but just noticed it is targeted to **master** branch, which is wrong. Could you resubmit your PR to **development** branch? thanks!!

**Comment by shangwen777** [comment]
Sure, I will do it tonight. Thanks for sharing the information.

**Comment by yzhao062** [comment]
Thanks for the PR. It is merged and updated (finally decide to refactor for consistency). Thanks for noting me on this and I also include you as the author of cblof.py (https://github.com/yzhao062/pyod/blob/development/pyod/models/cblof.py)

Let me know whether this information is accurate. Thanks again for spotting this.
Yue

**Comment by shangwen777** [comment]
Haha, I am Shangwen Huang. Although my husband’s last name is Lin. Nice
working with you!

Shangwen

**Comment by yzhao062** [comment]
LOL. I just did a search and use the name on facebook. Anyway, it is fixed now :)
