### ISSUE TITLE
Installation is broken due to missing sklearn.externals.funcsigs module

### ISSUE THREAD

**Issue by lavsurgut** [yzhao062/pyod#96]
Trying out to install pyod as usual
`pip install pyod`.
By default it uses now sklearn==0.21.0 which does not have sklearn.externals.funcsigs anymore.

Running
`from pyod.models.knn import KNN`
gives an error "No module named sklearn.externals.funcsigs"

Can be fixed by using scikit-learn<0.21

**Comment by yzhao062** [comment]
Exactly, sklearn 0.20.0 is the last version that supports Python 2.7. So sklearn drops funcsigs integration but calling "from inspect import signature". However, `signature` is not part of `inspect` on Python 2.7. 

One fix has been provided (has not yet been put on PyPI): https://github.com/yzhao062/pyod/commit/2a32eebe65d3aac4e47a7f73f0d98f285e8d5eb1
However, it will still fail on Python 2.7 with sklearn >=0.21.0. Will need to think about what is the best strategy.

**Comment by yzhao062** [comment]
My bad. Python 2.7 users would not be able to install sklearn 0.21. as sklearn 0.21 does not support Python 2 anymore (https://scikit-learn.org/stable/install.html). I will submit another pepy version soon.

**Comment by yzhao062** [comment]
Thanks again for reporting. v0.7.1 is released :)
