### ISSUE TITLE
Can we compare 3 features?

### ISSUE THREAD

**Issue by kusshal619** [yzhao062/pyod#99]
I wanted to know if it is possible to use PYOD for 3+ features. Most examples show 2 features.

**Comment by yzhao062** [comment]
of course. The examples are 2d only for **visualization** purpose (clearly we can only visualize it under dimension 3). In practice, you could use any reasonable number of features with it.

**Comment by kusshal619** [comment]
How would we modify the code for 3+ features?

xx , yy = np.meshgrid(np.linspace(0,1 , 200), np.linspace(0, 1, 200))

for i, (clf_name, clf) in enumerate(classifiers.items()):
    clf.fit(X)
    # predict raw anomaly score
    scores_pred = clf.decision_function(X) * -1
        
    # prediction of a datapoint category outlier or inlier
    y_pred = clf.predict(X)
    n_inliers = len(y_pred) - np.count_nonzero(y_pred)
    n_outliers = np.count_nonzero(y_pred == 1)
    plt.figure(figsize=(10, 10))
    
    # copy of dataframe
    dfx = df
    dfx['outlier'] = y_pred.tolist()
    
    # IX1 - inlier feature 1,  IX2 - inlier feature 2
    IX1 =  np.array(dfx['Item_MRP'][dfx['outlier'] == 0]).reshape(-1,1)
    IX2 =  np.array(dfx['Item_Outlet_Sales'][dfx['outlier'] == 0]).reshape(-1,1)
    
    # OX1 - outlier feature 1, OX2 - outlier feature 2
    OX1 =  dfx['Item_MRP'][dfx['outlier'] == 1].values.reshape(-1,1)
    OX2 =  dfx['Item_Outlet_Sales'][dfx['outlier'] == 1].values.reshape(-1,1)
         
    print('OUTLIERS : ',n_outliers,'INLIERS : ',n_inliers, clf_name)
        
    # threshold value to consider a datapoint inlier or outlier
    threshold = stats.scoreatpercentile(scores_pred,100 * outliers_fraction)
        
    # decision function calculates the raw anomaly score for every point
    Z = clf.decision_function(np.c_[xx.ravel(), yy.ravel()]) * -1
    Z = Z.reshape(xx.shape)
          
    # fill blue map colormap from minimum anomaly score to threshold value
    plt.contourf(xx, yy, Z, levels=np.linspace(Z.min(), threshold, 7),cmap=plt.cm.Blues_r)
        
    # draw red contour line where anomaly score is equal to thresold
    a = plt.contour(xx, yy, Z, levels=[threshold],linewidths=2, colors='red')
        
    # fill orange contour lines where range of anomaly score is from threshold to maximum anomaly score
    plt.contourf(xx, yy, Z, levels=[threshold, Z.max()],colors='orange')
        
    b = plt.scatter(IX1,IX2, c='white',s=20, edgecolor='k')
    
    c = plt.scatter(OX1,OX2, c='black',s=20, edgecolor='k')
       
    plt.axis('tight')  
    
    # loc=2 is used for the top left corner 
    plt.legend(
        [a.collections[0], b,c],
        ['learned decision function', 'inliers','outliers'],
        prop=matplotlib.font_manager.FontProperties(size=20),
        loc=2)
      
    plt.xlim((0, 1))
    plt.ylim((0, 1))
    plt.title(clf_name)
    plt.show()

**Comment by kusshal619** [comment]
Any update?

**Comment by yzhao062** [comment]
from the visualization perspective, it is almost impossible. I thought you want to compare the performance, then it is ok. But if you mean visualization, no. Do not spend too much time on 3d visualization for comparison purpose--it is not very worthy. Please try to use dimension reduction, e.g., PCA or t-SNE, to do 2d visualization. 

If you search online, you could see something like this 
![image](https://user-images.githubusercontent.com/15079146/58522032-9bc08200-818c-11e9-8286-b5f520df4efc.png)

But it is going to be complex to draw the decision boundary in 3D--it looks like this 
![image](https://user-images.githubusercontent.com/15079146/58522137-007bdc80-818d-11e9-9cd0-6b6f698728c1.png)

So the conclusion is, I would not recommend comparing visually in 3d space.

**Comment by kusshal619** [comment]
ok yes, I am kind of a python novice. For the above code if I do not want the graphics but only performance how would I modify it to take 3+ features? Could you please help me out.

**Comment by yzhao062** [comment]
nothing should be changed. Just make sure your input data has the shape like (n,3)-> n records, and each has 3 features. An example is here: https://github.com/yzhao062/pyod/blob/master/examples/auto_encoder_example.py

![image](https://user-images.githubusercontent.com/15079146/58522825-09ba7880-8190-11e9-8eb4-b078c8b5de0e.png)

I generate the data Xt_train with 300 features, and just fit the model with X_train.

**Comment by yzhao062** [comment]
Of course. you do not need to generate data. Just pass in X here:
![image](https://user-images.githubusercontent.com/15079146/58522910-471f0600-8190-11e9-99a5-0c49f58b5232.png)
You do not need to use autoencoder, but any models in PyOD.

**Comment by SungmanHong** [comment]
Amazing, thanks!
but i really want to code the visualization part...
